project:
  output-dir: _out

## Formats ##
format:
  aog-article-pdf:
    # Set alternative fonts here
    mainfont: Cambria
    sansfont: Helvetica
    linestretch: 1.5
    # use twoside
    #geometry: twoside

toc: true
number-sections: true

## Bibliography meta-information ##
reference-section-title: References # adjust name of reference section
bibliography: bibliography.bib
# You an also use a local CSL file
csl: https://www.zotero.org/styles/apa
